<?php

namespace Blixit\MSFBundle\Repository;

/**
 * MSFDataLoaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MSFDataLoaderRepository extends \Doctrine\ORM\EntityRepository
{
}
